name: Heater

on:
  schedule:
  - cron: '0 12 * * *'

  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run commit script
        run: |
          rand=$(shuf -i 1-4 -n 1)
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          for (( i=0; c!=$rand; i++ ))
          do 
            git commit --allow-empty -m ":art:"
          done
          git push origin main